### ISSUE TITLE
Analysis and Design of  UI for game

### ISSUE THREAD

**Issue by amdh** [amdh/202_Project1_Team16#11]

**Comment by Chaya16** [comment]
This basically involves deciding on tools to be used for building the game application. 
After looking through all the options decided on using the following though the team may use other tools if better options are  found. The list is as follows:
Greenfoot
Wireframes
MS Paint
Adobe Photoshop
iconfinder.com

**Comment by Chaya16** [comment]
Tools approved by team. Other options can be used as and when found.
