### ISSUE TITLE
Analysis and Design  of class model for treasure hunt( Class Diagram)

### ISSUE THREAD

**Issue by amdh** [amdh/202_Project1_Team16#12]

**Comment by amdh** [comment]
Classes needed :
Pirate , Place , Treasure , Hint, Enemy as Actors
Message to handle messages

**Comment by ArpitaDixit** [comment]
Need a class Button. Start button/ Show rules/ origin story button

**Comment by amdh** [comment]
Working on review comments..

**Comment by amdh** [comment]
updated as per comments
