### ISSUE TITLE
Architecture analysis and design  for treasure hunt(Use Case Diagram)

### ISSUE THREAD

**Issue by amdh** [amdh/202_Project1_Team16#21]

**Comment by Chaya16** [comment]
[UseCasediagramanddescription.docx](https://github.com/amdh/202_Project1_Team16/files/505275/UseCasediagramanddescription.docx)

**Comment by Chaya16** [comment]
[UseCasediagramanddescription.docx](https://github.com/amdh/202_Project1_Team16/files/505310/UseCasediagramanddescription.docx)
(Updated)

**Comment by Chaya16** [comment]
Reviewed and accepted by team, A missing arrow from Play game to Answer Hints Use Case.
