### ISSUE TITLE
Design Home Page

### ISSUE THREAD

**Issue by amdh** [amdh/202_Project1_Team16#37]
Designing various screens for the game

**Comment by amdh** [comment]
Creating screen for home page with all needed resources like background image, name for game and start option

**Comment by amdh** [comment]
uploaded home screen on gitup

**Comment by amdh** [comment]
references :

background image taken from : https://www.google.com/search?q=pirate+ship&rlz=1C1CHZL_enUS710US710&espv=2&biw=1745&bih=827&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiO0ryMsL3PAhVJ3mMKHaKSC3oQ_AUIBigB#imgrc=UMIJWmucFVgmXM%3A

background music taken from : http://stafaband.zone/mp3/download/pirates_of_the_caribbean_theme_song.html

treasure image taken from:
https://pixabay.com/en/pirate-treasure-coins-money-pirate-148526/

**Comment by Chaya16** [comment]
Include a button  with text "START GAME" in the home page

**Comment by amdh** [comment]
working on review comments

**Comment by amdh** [comment]
button added

**Comment by amdh** [comment]
design is reviewed and accepted by the team
