### ISSUE TITLE
DB design

### ISSUE THREAD

**Issue by AdityaParashar93** [amdh/202_Project1_Team16#44]

**Comment by AdityaParashar93** [comment]
[dbdesign.docx](https://github.com/amdh/202_Project1_Team16/files/505085/dbdesign.docx)
Here is the details of the db design.For now I am not closing the issue completely lets discuss the design in next meeting and then close the issue.

**Comment by ArpitaDixit** [comment]
In the player info table we need a column for time elapsed instead of score.  
Need to analyse whether storing images or path or url is more feasible.

**Comment by AdityaParashar93** [comment]
We will go with url in case of images and  will change the cx_score to cx_time while implementing.
